server:
  port: 8080

spring:
  application:
    name: service-01
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: chuonghoang
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    locations:
      classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
